### PR TITLE
ABJect

### PR DESCRIPTION
**Pull request by jfcoker**
Created a new executable for doing very simple coupling calculations. Use this if you want to find J between molecules A and B in a single dimer. Have also included some small quality of life updates.

### CODE REVIEW

**Review by jarvist — APPROVED** [review]
Looks good! Dragging that 2007 code into the modern era.

The hard-code to ~/pyMOO/bin is a bit clunky, but I suppose no worse than the previous expectation of ~/bin (though that's a more normal UNIX-thing.)

**Comment by jarvist** [comment]
Feel free to merge if you are happy; otherwise add more commits & I can review.

**Comment by jfcoker** [comment]
Thanks Jarv! Happy to merge the changes now, but I'm not currently a member of the group so don't think I'm allowed :(

**Comment by jarvist** [comment]
OK, I'll go sort permissions (assuming I'm still an admin.)

**Pull request merged**
